name: blue_thermal_printer_example
description: Demonstrates how to use the blue_thermal_printer plugin.
publish_to: https://pub.dev/packages/blue_thermal_printer

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  http: ^0.13.1
  charset_converter: ^2.2.0
  blue_thermal_printer: ^1.2.3
  flutter_blue_plus: ^1.32.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/yourlogo.png

